archetypes:
  Player:
    components:
      Name:
      Position:
      Health:
      Mana:
      Movement:
      Sprite:
        src:
          - 'character/nina.png'
          - 'character/ryu.png'
          - 'character/cray.png'
        walk: 6
        stand: 1

  Minion:
    components:
      Name:
      Position:
      Health:
      Movement:
      Target:
      Attack:
      Aggro:
      Sprite:
        src: 'character/robot.png'
        walk: 6
        stand: 1

  Nexus:
    components:
      Name:
      Position:
      Collision:
      Health:
      Target:
      Attack:
      Sprite:
        src: 'structure/base1.png'

  Turret:
    components:
      Name:
      Position:
      Collision:
      Health:
      Target:
      Attack:
      Aggro:
      Sprite:
        src: 'structure/tower1.png'

  Tree:
    components:
      Position:
      Collision:
      Sprite:
        src:
          - 'prop/tree1.png'
          - 'prop/tree2.png'
          - 'prop/tree3.png'
          - 'prop/tree4.png'

  Rock:
    components:
      Position:
      Collision:
      Sprite:
        src:
          - 'prop/rock1.png'
          - 'prop/rock2.png'
          - 'prop/rock3.png'
          - 'prop/rock4.png'