Character:
  components:
    venom.components.Position:
    venom.components.Movement:
      speed: 2
    venom.components.Sprite:
      src:
        - 'character/nina.png'
        - 'character/ryu.png'
        - 'character/cray.png'
      walk: 6
      stand: 1
    moba.components.Name:
    moba.components.Target:
    moba.components.Health:
      maximum: 1000
    moba.components.Mana:
      maximum: 1000
    moba.components.Attack:
      power: 5
    moba.components.Level:
    moba.components.Respawn:

Minion:
  components:
    venom.components.Position:
    venom.components.Movement:
      speed: 4
    venom.components.Sprite:
      src: 'character/robot.png'
      walk: 6
      stand: 1
    moba.components.Name:
      name: 'Minion'
    moba.components.Health:
      maximum: 50
    moba.components.Family:
    moba.components.Target:
    moba.components.Patrol:
      radius: 8
      rate: 10
    moba.components.Attack:
      power: 5
    moba.components.Aggro:
      radius: 3
    moba.components.Respawn:

Nexus:
  components:
    venom.components.Position:
    venom.components.Sprite:
      src: 'structure/base1.png'
    moba.components.Name:
      name: 'Nexus'
    moba.components.Health:
      maximum: 500
    moba.components.Target:
    moba.components.Respawn:

NexusPink:
  extend: Nexus
  components:
    venom.components.Sprite:
      src: 'structure/base6.png'

Turret:
  components:
    venom.components.Position:
    venom.components.Sprite:
      src: 'structure/tower1.png'
    moba.components.Name:
      name: 'Turret'
    moba.components.Health:
      maximum: 250
    moba.components.Target:
    moba.components.Attack:
      power: 5
      speed: 25
      projectile: Minion
    moba.components.Family:
    moba.components.Aggro:
      radius: 20
    moba.components.Respawn:

TurretPink:
  extend: Turret
  components:
    venom.components.Sprite:
      src: 'structure/tower2.png'
    moba.components.Attack:
      projectile: ProjectilePink

Projectile:
  components:
    venom.components.Position:
    venom.components.Movement:
    venom.components.Sprite:
      src: 'projectile/bolt-blue.png'
      walk: 3
    moba.components.Target:
    moba.components.Projectile:

ProjectilePink:
  extend: Projectile
  components:
    venom.components.Sprite:
      src: 'projectile/bolt-pink.png'
      walk: 3

Tree:
  components:
    venom.components.Position:
    venom.components.Collision:
    venom.components.Sprite:
      src:
        - 'prop/tree1.png'
        - 'prop/tree2.png'
        - 'prop/tree3.png'
        - 'prop/tree4.png'

Rock:
  components:
    venom.components.Position:
    venom.components.Collision:
    venom.components.Sprite:
      src:
        - 'prop/rock1.png'
        - 'prop/rock2.png'
        - 'prop/rock3.png'
        - 'prop/rock4.png'